# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "tf-yudi-state-2"
    encrypt = true
    key     = "tf-state/account/region/us-east-1/vpc/terraform.tfstate"
    profile = "darede-labs"
    region  = "us-east-2"
  }
}
