# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "terragruntatlantistfstate"
    encrypt = true
    key     = "tf-state/account/region/us-east-1/vpc/terraform.tfstate"
    profile = "default"
    region  = "sa-east-1"
  }
}
