# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "tf-state-761774289685"
    encrypt = true
    key     = "tf-state/account/region/us-east-1/vpc/terraform.tfstate"
    region  = "us-east-1"
  }
}
